---
title: "simecol Lotka-Volterra"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library("simecol")

lv.model <- new("odeModel",                   # object class = 'odeModel'
                
         main = function(time, y, parms) {   # object method
                                              # simecol magic: 2nd argument 'y' points to 'init'
          with(as.list(c(parms, y)), {

            dHARE <- (a - b * HARE - c * FOX) * HARE
            dFOX <- (-d + e * HARE) * FOX
            
            # a, b, c, d, and e are positive constants to be determined from field research.
            # writing dHARE = alpha * HARE, then alpha = a - b*HARE - c*FOX
            # which is the net birth rate for hares. When FOX=0, this is the logistics
            # equation. alpha is the intrinsic growth rate of hare 
            # a/b is the carrying capacity in the absence of fox.
            # if FOX > 0, the term -c*FOX*HARE models the predator effect of FOX
            #
            # net birth rate of FOX = -d + e*HARE
            # if HARE = 0, then FOX goes to 0
            # the term + e*HARE*FOX models the positive effect of hares on the birth
            # rate of foxes. 
          
            list(c(dFOX, dHARE))
           })
         },
         
         #.0078125
        times = seq(0, 50, .0078125), 
        parms = c(a=10, b=.5, c=1, d=1, e=1),
        init = c(FOX=10, HARE=25),
        solver = "euler"                      # 'lsoda' available for 'odemodel' class
        
      )
```


```{r}
lv.sim <- sim(lv.model)
plot(out(lv.sim)$FOX)
```


```{r}

plotupca <- function(obj, ...) {
  
  library(gridExtra)
  library(ggplot2)
  
  o.df <- out(obj)  # output a dataframe
  
  gg1 <- ggplot()  +
    geom_line(aes(x=time, y=HARE), o.df, colour = "purple", size=1, alpha=0.8)  +
    geom_line(aes(x=time, y=FOX), o.df, colour = "green", size=1, alpha=0.8)
  
  gg2 <- ggplot()  +
    geom_point(aes(x=FOX, y=HARE), o.df,  colour = "purple", alpha=0.6) 
  
  
  grid.arrange(gg1, gg2, ncol=2, nrow=1)

}

```

```{r}
 plotupca(lv.sim)
```

```{r}
head(out(lv.sim))
```

```{r}
main(lv.sim)
```

```{r}
init(lv.sim)
```

```{r}
parms(lv.sim)
```

```{r}
equations(lv.sim)
```

```{r}
solver(lv.sim)
```

```{r}
class(lv.sim)
```

```{r}
str(lv.sim)
```
