---
title: "simecol lorenz"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library("simecol")

lorenz.model <- new("odeModel",                   # object class = 'odeModel'
                
         main = function(times, y, parms) {   # object method
                                              # simecol magic: 2nd argument 'y' points to 'init'
          with(as.list(c(parms, y)), {

            horizTempVar <- convectiveFlow(convectiveFlowVar) * ( rayleigh - verticalTempDiff(verticalTempVar) ) - horizTempDiff(horizTempVar)
            verticalTempVar <- convectiveFlow(convectiveFlowVar) * horizTempDiff(horizTempVar) - height * verticalTempDiff(verticalTempVar)
            convectiveFlowVar <- prandtl * ( horizTempDiff(horizTempVar) - convectiveFlow(convectiveFlowVar) )
          
            list(c(horizTempDiff, verticalTempDiff, convectiveFlow))
           })
         },
         equations = list(
            horizTempDiff = function(i){(horizTempVar)},
            verticalTempDiff = function(i){verticalTempVar},
            convectiveFlow = function(i){convectiveFlowVar}
         ),
         
         #.0078125
        times = seq(0, 50, 1), 
        parms = c(prandtl=10, rayleigh=28, height=8/3),
        init = c(convectiveFlow=0, horizTempDiff=1, verticalTempDiff=0),
        solver = "rk4"                      # 'lsoda' available for 'odemodel' class
        
      )
```


```{r}
lorenz.sim <- sim(lorenz.model)
plot(lorenz.sim)
```


```{r}

plotupca <- function(obj, ...) {
  
  library(gridExtra)
  library(ggplot2)
  
  o.df <- out(obj)  # output a dataframe
  
  gg1 <- ggplot()  +
    geom_line(aes(x=time, y=horizTempDiff), o.df, colour = "purple", size=1, alpha=0.8)  +
    geom_line(aes(x=time, y=verticalTempDiff), o.df, colour = "green", size=1, alpha=0.8)
  
  gg2 <- ggplot()  +
    geom_line(aes(x=time, y=convectiveFlow), o.df,  colour = "purple", alpha=0.6) 
  
  
  grid.arrange(gg1, gg2, ncol=2, nrow=1)

}

```

```{r}
 plotupca(lorenz.sim)
```

```{r}
head(out(lorenz.sim))
```

```{r}
main(lorenz.sim)
```

```{r}
init(lorenz.sim)
```

```{r}
parms(lorenz.sim)
```

```{r}
equations(lorenz.sim)
```

```{r}
solver(lorenz.sim)
```

```{r}
class(lorenz.sim)
```

```{r}
str(lorenz.sim)
```
